#!/bin/bash

set -e 

mkdir -p /usr/lib/syslinux
ln /usr/lib/syslinux/modules/bios/ldlinux.c32 /usr/lib/syslinux/ldlinux.c32
ln /usr/lib/ISOLINUX/isolinux.bin /usr/lib/syslinux/isolinux.bin
ln /usr/lib/shim/shimx64.efi.signed /usr/lib/shim/shim.efi.signed
